resources:
  - name: mySecRepo
    type: GitRepo
    configuration:
      # SCM integration where the repository is located
      gitProvider: my_github # this will be replaced from values.yml
      # Repository path, including org name/repo name
      path: Krishna7777/jfrog-pipelines-second # this will be replaced from values.yml
      files: 
       include: ^README.md$
      branches:
        # Specifies which branches will trigger dependent steps
        include: ^{{gitBranch}}$
      
pipelines:
  - name: my_sec_pipeline
    steps:     
      - name: p1_s1
        type: Bash
        configuration:
          inputResources:
            # Sets up step to be triggered when there are commit events to myFirstRepo
            - name: mySecRepo
        execution:
          onExecute:
            # Data from input resources is available as env variables in the step
            - echo "Test"
            - echo $res_mySecRepo_commitSha
